CREATE DATABASE loadbalancing;

ALTER DATABASE loadbalancing OWNER TO postgres;

CREATE SCHEMA public;

ALTER SCHEMA public OWNER TO pg_database_owner;

CREATE TABLE public.users (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	date_of_birth timestamp NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id)
);